// Jenkinsfile (Declarative Pipeline)
pipeline {
    agent any

    stages {
//        stage('Check') {
//            steps {
//                sh './build.sh check'
//            }
//        }
        stage('Compile') {
            steps {
                sh './build.sh compile'
            }
        }
	stage('Run') {
	    steps {
		sh './build.sh run'
	    }
	}
        stage('Test') {
            steps {
                sh './build.sh test'
            }
        }
        stage('ShowTestResult') {
	    steps {
		junit allowEmptyResults: true, testResults: 'report/*.xml'
	    }
	}
        stage('SendEmail'){
	    steps{
            emailext body: '''<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define">
              <html>
                  <j:set var="cppcheckAction" value="${it.getAction(\'org.jenkinsci.plugins.cppcheck.CppcheckBuildAction\')}" />
                        <j:if test="${cppcheckAction!=null}">
                            <j:set var="cppcheckResult" value="${cppcheckAction.getResult()}" />
                                <j:if test="${cppcheckResult!=null}">
                                      <h2>Summary</h2>
                                              <style type="text/css">
                                                  #cppcheckStatistics { width: auto; }
                                                      #cppcheckStatistics .number { text-align: right; }
                                                              </style>
                                                                      <table class="pane sortable" id="cppcheckStatistics">
                                                                                <thead>
                                                                                            <tr>
                                                                                                          <td class="pane-header">Severity</td>
                                                                                                                        <td class="pane-header">Count</td>
                                                                                                                                      <td class="pane-header">Delta</td>
                                                                                                                                                  </tr>
                                                                                                                                                            </thead>
                                                                                                                                                                      <tbody>
                                                                                                                                                                                  <tr>
                                                                                                                                                                                                <td class="pane">Error</td>
                                                                                                                                                                                                              <td class="pane number">${cppcheckResult.statistics.getNumberErrorSeverity()}</td>
                                                                                                                                                                                                                            <td class="pane number">${cppcheckResult.getDiff().getNumberErrorSeverity()}</td>
                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                  <td class="pane">Warning</td>
                                                                                                                                                                                                                                                                                <td class="pane number">${cppcheckResult.statistics.getNumberWarningSeverity()}</td>
                                                                                                                                                                                                                                                                                              <td class="pane number">${cppcheckResult.getDiff().getNumberWarningSeverity()}</td>
                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                                    <td class="pane">Style</td>
                                                                                                                                                                                                                                                                                                                                                  <td class="pane number">${cppcheckResult.statistics.getNumberStyleSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                <td class="pane number">${cppcheckResult.getDiff().getNumberStyleSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                            </tr>
                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                      <td class="pane">Performance</td>
                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="pane number">${cppcheckResult.statistics.getNumberPerformanceSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <td class="pane number">${cppcheckResult.getDiff().getNumberPerformanceSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td class="pane">Portability</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td class="pane number">${cppcheckResult.statistics.getNumberPortabilitySeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="pane number">${cppcheckResult.getDiff().getNumberPortabilitySeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td class="pane">Information</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td class="pane number">${cppcheckResult.statistics.getNumberInformationSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td class="pane number">${cppcheckResult.getDiff().getNumberInformationSeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td class="pane">No category</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td class="pane number">${cppcheckResult.statistics.getNumberNoCategorySeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td class="pane number">${cppcheckResult.getDiff().getNumberNoCategorySeverity()}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tfoot>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <tr class="sortbottom">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td class="pane-header">Total</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td class="pane-header number"><B><a href="${rooturl}${build.url}cppcheckResult">${cppcheckResult.report.getNumberTotal()}</a></B></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td class="pane-header number"><B><a href="${rooturl}${build.url}cppcheckResult/source.all/?before=5&amp;after=5&amp;states=new">${cppcheckResult.getDiff().getNumberTotal()}</a></B></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tfoot>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </j:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </j:if>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </j:jelly>''', subject: 'build complete', to: 'xinjiayang@deepglint.com'

	    }
	}
	stage('End') {
	    steps {
		sh "./build.sh end"
	    }
	}
    }
}
